Add OpenLayers support
geojupyter/jupytergis pull request #112
Opened 2024-08-27 11:52 UTC by gjmooney

Super rough draft of adding an OpenLayers viewer and fancy color things. 

![geotiff_color_bands](https://github.com/user-attachments/assets/bf36abff-e049-42c4-a98e-c2171ef7b6e0)

2024-09-03 13:42 UTC, martinRenou requested changes
Thank you for this! It's quite a huge PR 🚀 

- I think we're missing an `@import url('ol/ol.css');` in our CSS, maybe in `packages/base/style/base.css`. OpenLayers is not styled properly.
- The brush icon in the toolbar is mal-positioned I believe. Because for now this button only makes sense for Geotiff layers (or does it not?). I would put it in the properties panel for the geotiff layer when clicking on the layer.
- When selecting the geotiff layer in `geotiff.jGIS` file, the properties panel seems confused about the form being generated and show lots of errors
- the `pmtiles-vector.jGIS` example does not show the vector pmtiles layer anymore
- I would remove the `console.log` calls here and there (mostly in `packages/base/src/dialogs/colorExpressionDialog.tsx`)

2024-09-03 13:42 UTC, martinRenou commented on packages/base/src/formbuilder/objectform/vectorlayerform.ts
> -      'ui:widget': 'color'
This seems to break the color picker for the GeoJSON layer properties panel

2024-09-03 13:42 UTC, martinRenou commented on python/jupytergis_lab/src/index.ts
> +    // });
Let's remove these

```suggestion
```

2024-09-03 13:42 UTC, martinRenou commented on python/jupytergis_lab/src/index.ts
> +    // });
```suggestion
```

2024-09-03 13:42 UTC, martinRenou commented on ui-tests/tests/notebook.spec.ts-snapshots/light-Notebook-ipynb-cell-2-linux.png
This may be because OpenLayers is less performant than Maplibre and we'll now need to wait a bit before making the screenshot?

2024-09-03 13:42 UTC, martinRenou commented on packages/base/src/mainview/mainViewOl.tsx
> +
You commented this, do we still need it?

```suggestion
```

2024-09-03 13:42 UTC, martinRenou commented on packages/base/src/toolbar/widget.tsx
> +
```suggestion
```

2024-09-03 13:42 UTC, martinRenou commented on packages/base/src/formbuilder/objectform/vectorlayerform.ts
> +    // };
```suggestion
```

2024-09-03 13:42 UTC, martinRenou commented on packages/base/src/formbuilder/objectform/vectorlayerform.ts
> -      'ui:widget': 'color'
We may need some fancy new color widget here instead of the default one RJSF provides.

Let's probably keep that for a future PR

2024-09-03 13:42 UTC, martinRenou commented on packages/base/src/formbuilder/objectform/baseform.tsx
> +// };
I guess this is a custom color widget you wanted to introduce? Let's doododoododoass it from the file for now 😆 

```suggestion
```

2024-09-03 13:42 UTC, martinRenou commented on packages/base/src/toolbar/widget.tsx
> +        'zoomColor',
I am a bit confused by the name "zoomColor" and how you are using your color stops.

- I understood that the color stop widget was for defining color stops (and interpolate between those) given a data channel from the geotiff. I don't see in your implementation how the data channel is being used? 
- I also don't understand how it's related to zoom, is it a name from an old implementation?

2024-09-03 14:57 UTC, martinRenou commented on packages/base/src/toolbar/widget.tsx
> +        'zoomColor',
As discussed in-person:

>  I also don't understand how it's related to zoom, is it a name from an old implementation?

It is indeed a name from an old implementation

> I don't see in your implementation how the data channel is being used?

This is not yet fully exposed to the UI, we will need to iterate on the UI to be able to select bands and apply styling to them

2024-09-03 15:55 UTC, martinRenou requested changes

2024-09-03 15:55 UTC, martinRenou commented on packages/base/package.json
>      "maplibre-gl": "^4.4.1",
Should we remove maplibre now? I guess it's not used anymore?

2024-09-03 15:57 UTC, gjmooney commented
>     * When selecting the geotiff layer in `geotiff.jGIS` file, the properties panel seems confused about the form being generated and show lots of errors

I'm not sure how to handle this, I tried hiding the color field, but the errors still show up.

2024-09-03 16:00 UTC, martinRenou commented
> I'm not sure how to handle this, I tried hiding the color field, but the errors still show up.

Yes, let's handle this in a follow-up PR with a new fancy color widget

2024-09-04 06:35 UTC, martinRenou commented
bot please update snapshots

2024-09-04 07:58 UTC, martinRenou approved these changes
Thanks Greg! Let's go with this and iterate.

We'll need to rework the color selection widgets in the properties panel

2024-09-04 07:58 UTC, merged