Start implementing follow
geojupyter/jupytergis pull request #257
Opened 2024-12-17 11:28 UTC by gjmooney

Starting on #218

2024-12-17 15:48 UTC, mfisher87 commented on packages/schema/src/interfaces.ts
> +export type CenterPosition = {
Nice! Hope you don't mind me leaving a comment on your draft :) 

Nit: I feel this name would work better if not for the `zoom` attribute. What about `ViewportPosition` or `ViewportState`?

2024-12-17 15:53 UTC, mfisher87 commented on packages/schema/src/model.ts
> +  syncCenter(center?: CenterPosition, emitter?: string): void {
`syncViewport`?

2024-12-18 14:56 UTC, gjmooney commented
please update snapshots

2024-12-20 02:13 UTC, mfisher87 approved these changes
:star_struck:

2024-12-20 10:43 UTC, martinRenou requested changes
Thanks!

I'm not sure how the visual regression tests are passing.

For me the map is always opening at the same initial position, not respecting the position saved in the file anymore:

https://github.com/user-attachments/assets/bd816287-46b0-49ea-bd5a-f367b619bd53

2024-12-20 11:35 UTC, gjmooney commented
> Thanks!
> 
> I'm not sure how the visual regression tests are passing.
> 
> For me the map is always opening at the same initial position, not respecting the position saved in the file anymore:

It looks like `view.animate` is undefined at first? So the lat/lng was getting reset to 0. I'm gonna assume the regression tests are slow enough that it wasn't an issue with them. Adding a check and `setCenter`/`setZoom` as a fallback seems to work.

2024-12-20 12:39 UTC, martinRenou approved these changes
Thanks!!

2024-12-20 12:39 UTC, merged