[WIP] Add ReadTheDocs build
geojupyter/jupytergis pull request #275
Opened 2024-12-27 05:47 UTC by mfisher87

We're most of the way there, I think, but the jupyterlite-sphinx build step is failing and I'm struggling to diagnose. I can build the environment from `docs/environment.yml` on my local machine, but the RTD build seems to be choking on the same env, but only during the jupyterlite build step. The log seems a bit jumbled, which isn't helping!

https://app.readthedocs.org/projects/jupytergis-test/builds/26694261/

```
Looking for: ['python=3.10', 'pip', "jupyterlite-core[version='>=0.2.0,<0.3.0']", "jupyterlite-xeus[version='>=0.1.2,<0.2']", 'jupyterlite-sphinx', 'sphinx', 'sphinx-tabs', 'pydata-sphinx-theme', 'sphinx-autodoc-typehints', 'sphinx', 'emscripten-abi=3.1.45']

Could not solve for environment specs
The following packages are incompatible
├─ jupyterlite-core >=0.2.0,<0.3.0  is not installable because it requires
│  └─ jupyter_core >=4.7  but there are no viable options
│     ├─ jupyter_core 5.7.2 would require
│     │  └─ __unix, which is missing on the system;
│     └─ jupyter_core 5.7.2 would require
│        └─ __win, which is missing on the system;
├─ jupyterlite-sphinx is not installable because it requires
│  └─ jupyter_server but there are no viable options
│     ├─ jupyter_server [1.10.0|1.10.1|...|1.9.0] would require
│     │  └─ tornado >=6.1 , which does not exist (perhaps a missing channel);
│     ├─ jupyter_server [1.13.4|1.13.5|...|1.24.0] would require
│     │  └─ pyzmq >=17 , which does not exist (perhaps a missing channel);
│     └─ jupyter_server [2.0.0|2.0.1|...|2.9.1] would require
│        └─ tornado >=6.2.0 , which does not exist (perhaps a missing channel);
├─ jupyterlite-xeus >=0.1.2,<0.2  is not installable because it requires
│  └─ jupyterlite-core [>=0.1,<0.4 |>=0.2,<0.3 ], which cannot be installed (as previously explained);
└─ python 3.10**  does not exist (perhaps a typo or a missing channel).
[LiteBuildApp] ERROR | [lite] [post_build] [jupyterlite-xeus] [ERR] Command '['/home/docs/.asdf/shims/mamba', 'install', '--yes', '--prefix', PosixPath('/tmp/tmptr_ray7k/env/envs/jupytergis-docs'), '-c', 'https://repo.mamba.pm/emscripten-forge', '-c', 'conda-forge', 'python=3.10', 'pip', 'jupyterlite-core>=0.2.0,<0.3.0', 'jupyterlite-xeus>=0.1.2,<0.2', 'jupyterlite-sphinx', 'sphinx', 'sphinx-tabs', 'pydata-sphinx-theme', 'sphinx-autodoc-typehints', 'sphinx', 'emscripten-abi=3.1.45']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/doit_cmd.py", line 294, in run
    return command.parse_execute(args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/cmd_base.py", line 570, in execute
    return self._execute(**exec_params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/cmd_run.py", line 265, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/runner.py", line 254, in run_all
    self.run_tasks(task_dispatcher)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/runner.py", line 213, in run_tasks
    node = task_dispatcher.generator.send(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/control.py", line 629, in _dispatcher_generator
    next_step = node.step()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/control.py", line 336, in step
    return next(self.generator)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/control.py", line 345, in _func
    for value in decorated(*args, **kwargs):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/control.py", line 473, in _add_task
    new_tasks = generate_tasks(to_load, task_gen, ref.__doc__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/loader.py", line 390, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/doit/loader.py", line 27, in flat_generator
    for item in gen:
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_core/manager.py", line 138, in _delayed_gather
    yield from _gather()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_core/manager.py", line 131, in _gather
    raise error
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_core/manager.py", line 123, in _gather
    for task in getattr(addon, attr)(self):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_xeus/add_on.py", line 124, in post_build
    self.create_prefix()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_xeus/add_on.py", line 148, in create_prefix
    create_conda_env_from_env_file(root_prefix, yaml_content, env_file.parent)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_xeus/create_conda_env.py", line 55, in create_conda_env_from_env_file
    create_conda_env_from_specs(
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_xeus/create_conda_env.py", line 71, in create_conda_env_from_specs
    _create_conda_env_from_specs_impl(
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_xeus/create_conda_env.py", line 128, in _create_conda_env_from_specs_impl
    return _create_env_with_config(MAMBA_COMMAND, prefix_path, specs, channels_args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/site-packages/jupyterlite_xeus/create_conda_env.py", line 146, in _create_env_with_config
    subprocess_run(
  File "/home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/conda/latest/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/docs/.asdf/shims/mamba', 'install', '--yes', '--prefix', PosixPath('/tmp/tmptr_ray7k/env/envs/jupytergis-docs'), '-c', 'https://repo.mamba.pm/emscripten-forge', '-c', 'conda-forge', 'python=3.10', 'pip', 'jupyterlite-core>=0.2.0,<0.3.0', 'jupyterlite-xeus>=0.1.2,<0.2', 'jupyterlite-sphinx', 'sphinx', 'sphinx-tabs', 'pydata-sphinx-theme', 'sphinx-autodoc-typehints', 'sphinx', 'emscripten-abi=3.1.45']' returned non-zero exit status 1.
[LiteBuildApp] Exiting application: jupyter
static:jupyter-lite.json
.  pre_status:static:jupyter-lite.json
    tarball:         jupyterlite-app-0.2.3.tgz 9MB
    output:          /home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/checkouts/latest/_readthedocs/html/lite
    lite dir:        /home/docs/checkouts/readthedocs.org/user_builds/jupytergis-test/checkouts/latest/docs
    apps:            notebooks, edit, lab, repl, tree, consoles
    sourcemaps:      True
    unused packages: True
archive:archive [...]

2024-12-27 07:20 UTC, mfisher87 commented on docs/environment.yml
I think my sin was playing with this without understanding its purpose. It's being implicitly used by the jupyterlite build step, I think.

2024-12-27 07:32 UTC, mfisher87 commented
I am confused how I managed to break linting :laughing:

2024-12-27 07:33 UTC, mfisher87 commented on docs/environment.yml
I'd like to document this in a comment in the file, ideally with a link to relevant documentation. If anyone can help save me some time on this, I'd really appreciate it ;)

2024-12-27 07:42 UTC, mfisher87 commented on docs/environment.yml
Yes, I'm starting to piece things together. `emscripten` is conda's WASM platform that's used during the jupyterlite build step (of course!), which explains the failure to solve the environment when I put all that other junk in there. The version of conda in readthedocs looks to be too old to support the new platform?

This is super cool to start to understand :)

2024-12-27 21:19 UTC, mfisher87 commented
Working! JupyterLite in RTD: https://jupytergis--275.org.readthedocs.build/en/275/lite/lab/index.html?path=france_hiking.jGIS

2024-12-27 22:49 UTC, mfisher87 commented
The docs index page now has a badge linking to the lite deployment.

2024-12-28 18:57 UTC, mfisher87 commented
Ack how did I break this

2024-12-28 19:03 UTC, mfisher87 commented
Is the build perhaps a bit flaky? The only change between successful build and failing build was a pull request "opened" automation:

https://github.com/geojupyter/jupytergis/compare/f498a5e73fb7a46216676cd71ac530f9e0f37a61...4cd79b92fc7ac1300f3b5a273ea0b8bdfcddd21d

Failed: https://app.readthedocs.org/projects/jupytergis/builds/26699339/
Passed: https://app.readthedocs.org/projects/jupytergis/builds/26699052/

2024-12-28 19:05 UTC, mfisher87 commented
The check links failure was caused by the new jupyterlite button in the docs that I added. It's a relative link to `lite/`, and the link checker seems to be assuming that all relative links will have a corresponding file in the source. Perhaps we can tell the link checker to ignore that. I haven't started looking yet :)

2024-12-28 19:06 UTC, mfisher87 commented
> Is the build perhaps a bit flaky?

Looks like yes, re-running the build on the latest commit passed it: https://app.readthedocs.org/projects/jupytergis/builds/26702609/

2024-12-28 19:25 UTC, mfisher87 commented
Wat? Now only 4 checks are running? Is GitHub Actions having a problem? There should be 12 checks.

![image](https://github.com/user-attachments/assets/abf05192-a912-44f6-8858-af44f1fa8130)

GitHub is not claiming any outage... but I don't see how my change adding inputs to the check links action could cause 8 actions to not run. I'm going to push the commit again and see what happens.

2024-12-28 19:26 UTC, mfisher87 commented
Yup, re-pushing the commit triggered all the actions. It must be an issue on GitHub's side that they're not aware of yet.

2024-12-28 19:29 UTC, mfisher87 commented
Link check is fixed by ignoring the `lite/` link in GHA config.

2024-12-28 19:50 UTC, mfisher87 commented on .readthedocs.yaml
> +      - >-
The more I look at the command below, the more I feel this isn't super readable. Most readers probably expect the line break to indicate end of the command, but the `>` folding style operator I chose (why? :shrug: I forgot) violates that intuition. I'm thinking we should switch to `|` literal style and escape the newlines to be more intuitive.

2024-12-28 19:53 UTC, mfisher87 commented on .readthedocs.yaml
> +      - >-
63f605f

What do y'all think?

2025-01-02 10:22 UTC, brichet commented
@mfisher87 thanks for working on it.

> I am still confused how I managed to break linting 😆

It seems to be mostly about quotes, to fix it you can run `jlpm lint` locally and commit the modified files.

2025-01-02 11:12 UTC, brichet requested changes
@mfisher87 thanks for working on it.

> Looks like linting is failing unrelated to my change -- perhaps a new release of typescript-eslint modifying detection logic or fixing a bug that was producing false negatives? What's y'all's preference? Deal with the linter errors in this PR or in another PR?

It seems to be mostly about quotes, to fix it you can run `jlpm lint` locally and commit the modified files.

2025-01-02 16:04 UTC, mfisher87 commented
No problem, on it! I was wondering whether, as a rule, this team prefers unrelated linting fixes to be bundled with any old' PR, or to separate them to make reviews easy. I suppose in this case since there's only 3 lint fixes, the consequences to reviewability aren't large so it's more a curiosity about how y'all prefer to work in the future :)

2025-01-02 16:37 UTC, mfisher87 commented
Lint is just failing with no errors in CI now. It passes on my local machine.

2025-01-02 16:59 UTC, gjmooney commented
> Lint continued to fail in CI on the same rule, even after disabling it and passing lint on my local machine. I rebased the PR on `main` and now lint is just failing with no errors in CI. It still passes locally. Any ideas would be very appreciated!

You need single quotes instead of double quotes in `.github/dependabot.yml`,
`.github/workflows/build.yml`, and `.github/workflows/pr-rtd-link.yml`, and you have extra spaces in `docs/environment-docs.yml`

If you run `jlpm lint` locally is should automatically fix those, or `jlpm lint:check` to get a list of files that need fixing.

2025-01-02 18:15 UTC, mfisher87 commented
Thanks all! The lint warnings were a red herring, and I completely ignored the filenames being output by the prettier check. It's also confusing that `jlpm run lint` will find errors and apply fixes and return `0` :) Based on previous experience with autofixers, I thought that the check passed and it did nothing!

I posted in #280 that I'd like to move all the formatting checks into pre-commit to avoid the confusing failures in CI. Thoughts?

2025-01-02 18:19 UTC, mfisher87 commented
Merge #280 first to fix dependabot config

2025-01-03 09:20 UTC, brichet commented
@mfisher87 I merged main to trigger again the check-release test.

2025-01-03 10:37 UTC, brichet approved these changes
Thanks @mfisher87, this looks good to me

2025-01-03 10:38 UTC, merged